name = "gastos"
compatibility_date = "2026-08-01"
main = "src/index.js"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "gastos"
database_id = "PEGAR-ACA-EL-ID-QUE-DEVUELVE-WRANGLER"
